/*
Script generated by Aqua Data Studio 22.1.2 on Feb-26-2022 11:26:28 AM
Database: VARS_KB
Schema: dbo
Objects: TABLE, VIEW, INDEX
*/
CREATE TABLE Concept  ( 
	id                	bigint PRIMARY KEY NOT NULL,
	ParentConceptID_FK	bigint NULL,
	Originator        	varchar(255) NULL,
	StructureType     	varchar(10) NULL,
	Reference         	varchar(1024) NULL,
	NodcCode          	varchar(20) NULL,
	RankName          	varchar(20) NULL,
	RankLevel         	varchar(20) NULL,
	TaxonomyType      	varchar(20) NULL,
	AphiaId				bigint NULL,
	LAST_UPDATED_TIME 	timestamp NOT NULL DEFAULT now());

CREATE TABLE ConceptDelegate  ( 
	id               	bigint PRIMARY KEY NOT NULL,
	ConceptID_FK     	bigint NOT NULL,
	LAST_UPDATED_TIME	timestamp NULL,
	CONSTRAINT fk_ConceptDelegage__Concept_id  
	  FOREIGN KEY(ConceptID_FK) 
		REFERENCES Concept(id));

CREATE TABLE Artifact  ( 
	id                  	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK	bigint NOT NULL,
	GroupId             	varchar(64) NOT NULL,
	ArtifactId          	varchar(256) NOT NULL,
	Version             	varchar(64) NOT NULL,
	Classifier          	varchar(64) NULL,
	Description         	varchar(2048) NULL,
	MimeType            	varchar(32) NULL,
	Caption             	varchar(1024) NULL,
	Reference           	varchar(1024) NOT NULL,
	Credit              	varchar(1024) NULL,
	LAST_UPDATED_TIME   	timestamp NOT NULL DEFAULT now(),
	CreationDate        	timestamp NOT NULL DEFAULT now(),
	CONSTRAINT fk_Artifact__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE ConceptName  ( 
	id               	bigint PRIMARY KEY NOT NULL,
	ConceptName      	varchar(128) NULL,
	ConceptID_FK     	bigint NULL,
	Author           	varchar(255) NULL,
	NameType         	varchar(10) NULL,
	LAST_UPDATED_TIME	timestamp NOT NULL DEFAULT now(),
	UNIQUE(ConceptName),
	CONSTRAINT fk_ConceptName__Concept_id
	  FOREIGN KEY(ConceptID_FK) 
		REFERENCES Concept(id));

CREATE TABLE History  ( 
	id                  	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK	bigint NULL,
	ProcessedDTG        	timestamp NULL,
	CreationDTG         	timestamp NULL,
	Description         	varchar(1000) NULL,
	CreatorName         	varchar(50) NULL,
	ProcessorName       	varchar(50) NULL,
	Field               	varchar(50) NULL,
	OldValue            	varchar(2048) NULL,
	NewValue            	varchar(2048) NULL,
	Action              	varchar(16) NULL,
	Comment             	varchar(2048) NULL,
	Approved            	smallint NOT NULL,
	LAST_UPDATED_TIME   	timestamp NOT NULL DEFAULT now(),
	CONSTRAINT fk_History__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE LinkRealization  ( 
	id                  	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK	bigint NULL,
	LinkName            	varchar(50) NULL,
	ToConcept           	varchar(128) NULL,
	LinkValue           	varchar(2048) NULL,
	LAST_UPDATED_TIME   	timestamp NOT NULL DEFAULT now(),
	CONSTRAINT fk_LinkRealization__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE LinkTemplate  ( 
	id                  	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK	bigint NULL,
	LinkName            	varchar(50) NULL,
	ToConcept           	varchar(128) NULL,
	LinkValue           	varchar(2048) NULL,
	LAST_UPDATED_TIME   	timestamp NOT NULL DEFAULT now(),
	CONSTRAINT fk_LinkTempate__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE Media  ( 
	id                  	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK	bigint NULL,
	Url                 	varchar(1024) NULL,
	MediaType           	varchar(5) NULL,
	PrimaryMedia        	smallint NULL,
	Credit              	varchar(255) NULL,
	Caption             	varchar(1000) NULL,
	LAST_UPDATED_TIME   	timestamp NOT NULL DEFAULT now(),
	CONSTRAINT fk_Media__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE Prefs  ( 
	NodeName 	varchar(255) NOT NULL,
	PrefKey  	varchar(50) NOT NULL,
	PrefValue	varchar(255) NOT NULL,
	PRIMARY KEY (NodeName, PrefKey));

CREATE TABLE SectionInfo  ( 
	id                  	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK	bigint NOT NULL,
	Header              	varchar(30) NOT NULL,
	Label               	varchar(50) NOT NULL,
	Information         	varchar(5000) NULL,
	CONSTRAINT fk_SectionInfo__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE Reference (
	id bigint PRIMARY KEY NOT NULL,
	LAST_UPDATED_TIME timestamp(6), 
	citation varchar(2048) not null, 
	doi varchar(2048) unique);

CREATE TABLE Reference_ConceptDelegate (
	ConceptDelegateID_FK bigint not null, 
	ReferenceID_FK bigint not null, 
	primary key (ConceptDelegateID_FK, ReferenceID_FK),
	CONSTRAINT fk_RCD__ConceptDelegate_id foreign key (ConceptDelegateID_FK) references ConceptDelegate,
	CONSTRAINT fk_RCD__Reference_id foreign key (ReferenceID_FK) references Reference);


CREATE TABLE UniqueID  ( 
	tablename	varchar(200) NOT NULL,
	nextid   	bigint NULL,
	PRIMARY KEY (tablename));

CREATE TABLE Usage  ( 
	id                   	bigint PRIMARY KEY NOT NULL,
	ConceptDelegateID_FK 	bigint NULL,
	EmbargoExpirationDate	timestamp NULL,
	Specification        	varchar(1000) NULL,
	LAST_UPDATED_TIME    	timestamp NOT NULL DEFAULT now(),
	CONSTRAINT fk_Usage__ConceptDelegate_id
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate(id));

CREATE TABLE UserAccount  ( 
	id               	bigint PRIMARY KEY NOT NULL,
	UserName         	varchar(50) NOT NULL,
	Password         	varchar(50) NULL,
	Role             	varchar(10) NULL,
	LAST_UPDATED_TIME	timestamp NOT NULL DEFAULT now(),
	Affiliation      	varchar(50) NULL,
	FirstName        	varchar(50) NULL,
	LastName         	varchar(50) NULL,
	Email            	varchar(50) NULL,
	UNIQUE(UserName));

create table Reference (
    id        bigint PRIMARY KEY NOT NULL,
	LAST_UPDATED_TIME timestamp NOT NULL DEFAULT now(),
    citation  varchar(2048) not null,
    doi       varchar(2048) NULL);

-- alter table if exists Reference_ConceptDelegate add constraint fk_RCD__ConceptDelegate_id foreign key (ConceptDelegateID_FK) references ConceptDelegate;
-- alter table if exists Reference_ConceptDelegate add constraint fk_RCD__Reference_id foreign key (ReferenceID_FK) references Reference;

create table Reference_ConceptDelegate (
	ConceptDelegateID_FK bigint not null, 
	ReferenceID_FK bigint not null, 
	primary key (ConceptDelegateID_FK, ReferenceID_FK),
	CONSTRAINT fk_RCD__ConceptDelegate_id
		FOREIGN KEY(ConceptDelegateID_FK) 
			REFERENCES ConceptDelegate(id),
	CONSTRAINT fk_RCD__Reference_id
		FOREIGN KEY(ReferenceID_FK) 
			REFERENCES Reference(id));

CREATE UNIQUE INDEX idx_Artifact__special1
	ON Artifact(ConceptDelegateID_FK, GroupId, ArtifactId, Version, Classifier);

CREATE INDEX idx_Artifact__ConceptDelegateID_FK
	ON Artifact(ConceptDelegateID_FK);

CREATE INDEX idx_Artifact__LAST_UPDATED_TIME
	ON Artifact(LAST_UPDATED_TIME);

CREATE  INDEX idx_ConceptDelegate__ConceptID_FK
	ON ConceptDelegate(ConceptID_FK);

CREATE  INDEX idx_ConceptDelegate__LAST_UPDATED_TIME
	ON ConceptDelegate(LAST_UPDATED_TIME);

CREATE  INDEX idx_ConceptName__ConceptID_FK
	ON ConceptName(ConceptID_FK);

CREATE  INDEX idx_ConceptName__LAST_UPDATED_TIME
	ON ConceptName(LAST_UPDATED_TIME);

CREATE  INDEX idx_ConceptName__ConceptName
	ON ConceptName(ConceptName);

CREATE  INDEX idx_Concept__ParentConceptID_FK
	ON Concept(ParentConceptID_FK);

CREATE  INDEX idx_Concept__LAST_UPDATED_TIME
	ON Concept(LAST_UPDATED_TIME);

CREATE  INDEX idx_History__ConceptDelegateID_FK
	ON History(ConceptDelegateID_FK);

CREATE  INDEX idx_History__LAST_UPDATED_TIME
	ON History(LAST_UPDATED_TIME);

CREATE  INDEX idx_LinkRealization__ConceptDelegateID_FK
	ON LinkRealization(ConceptDelegateID_FK);

CREATE  INDEX idx_LinkRealization__LAST_UPDATED_TIME
	ON LinkRealization(LAST_UPDATED_TIME);

CREATE  INDEX idx_LinkTemplate__ConceptDelegateID_FK
	ON LinkTemplate(ConceptDelegateID_FK);

CREATE  INDEX idx_LinkTemplate__LAST_UPDATED_TIME
	ON LinkTemplate(LAST_UPDATED_TIME);

CREATE  INDEX idx_Media__LAST_UPDATED_TIME
	ON Media(LAST_UPDATED_TIME);

CREATE  INDEX idx_Prefs
	ON Prefs(NodeName, PrefKey);

CREATE  INDEX idx_SectionInfo__ConceptDelegateID_FK
	ON SectionInfo(ConceptDelegateID_FK);

CREATE  INDEX idx_Usage__ConceptDelegateID_FK
	ON Usage(ConceptDelegateID_FK);

CREATE  INDEX idx_Usage__LAST_UPDATED_TIME
	ON Usage(LAST_UPDATED_TIME);

CREATE  INDEX idx_UserAccount__UserName
	ON UserAccount(UserName);

