/*
Script generated by Aqua Data Studio 22.1.2 on Feb-26-2022 11:26:28 AM
Database: VARS_KB
Schema: dbo
Objects: TABLE, VIEW, INDEX
*/
CREATE TABLE Concept  ( 
	"id"                	bigint PRIMARY KEY NOT NULL,
	"ParentConceptID_FK"	bigint NULL,
	"Originator"        	varchar(255) NULL,
	"StructureType"     	varchar(10) NULL,
	"Reference"         	varchar(1024) NULL,
	"NodcCode"          	varchar(20) NULL,
	"RankName"          	varchar(20) NULL,
	"RankLevel"         	varchar(20) NULL,
	"TaxonomyType"      	varchar(20) NULL,
	"LAST_UPDATED_TIME" 	timestamp NULL);

CREATE TABLE ConceptDelegate  ( 
	"id"               	bigint PRIMARY KEY NOT NULL,
	"ConceptID_FK"     	bigint NOT NULL,
	"LAST_UPDATED_TIME"	timestamp NULL, 
	CONSTRAINT fk_concept_delegate__concept 
	  FOREIGN KEY(ConceptID_FK) 
		REFERENCES Concept("id"));

CREATE TABLE "Artifact"  ( 
	"id"                  	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK"	bigint NOT NULL,
	"GroupId"             	varchar(64) NOT NULL,
	"ArtifactId"          	varchar(256) NOT NULL,
	"Version"             	varchar(64) NOT NULL,
	"Classifier"          	varchar(64) NULL,
	"Description"         	varchar(2048) NULL,
	"MimeType"            	varchar(32) NULL,
	"Caption"             	varchar(1024) NULL,
	"Reference"           	varchar(1024) NOT NULL,
	"Credit"              	varchar(1024) NULL,
	"LAST_UPDATED_TIME"   	timestamp NOT NULL,
	"CreationDate"        	timestamp NULL,
	CONSTRAINT fk_artifact__concept_delegate
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate("id"));

CREATE TABLE "ConceptName"  ( 
	"id"               	bigint PRIMARY KEY NOT NULL,
	"ConceptName"      	varchar(128) NULL,
	"ConceptID_FK"     	bigint NULL,
	"Author"           	varchar(255) NULL,
	"NameType"         	varchar(10) NULL,
	"LAST_UPDATED_TIME"	timestamp NULL,
	UNIQUE("ConceptName"),
	CONSTRAINT fk_concept_name__concept
	  FOREIGN KEY(ConceptID_FK) 
		REFERENCES Concept("id"));

CREATE TABLE "History"  ( 
	"id"                  	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK"	bigint NULL,
	"ProcessedDTG"        	timestamp NULL,
	"CreationDTG"         	timestamp NULL,
	"Description"         	varchar(1000) NULL,
	"CreatorName"         	varchar(50) NULL,
	"ProcessorName"       	varchar(50) NULL,
	"Field"               	varchar(50) NULL,
	"OldValue"            	varchar(2048) NULL,
	"NewValue"            	varchar(2048) NULL,
	"Action"              	varchar(16) NULL,
	"Comment"             	varchar(2048) NULL,
	"Approved"            	smallint NOT NULL,
	"LAST_UPDATED_TIME"   	timestamp NULL,
	CONSTRAINT fk_history__concept_delegate
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate("id"));

CREATE TABLE "LinkRealization"  ( 
	"id"                  	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK"	bigint NULL,
	"LinkName"            	varchar(50) NULL,
	"ToConcept"           	varchar(128) NULL,
	"LinkValue"           	varchar(2048) NULL,
	"LAST_UPDATED_TIME"   	timestamp NULL,
	CONSTRAINT fk_link_realization__concept_delegate
	  FOREIGN KEY(ConceptDelegateID_FK) 
		REFERENCES ConceptDelegate("id"));

CREATE TABLE "LinkTemplate"  ( 
	"id"                  	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK"	bigint NULL,
	"LinkName"            	varchar(50) NULL,
	"ToConcept"           	varchar(128) NULL,
	"LinkValue"           	varchar(2048) NULL,
	"LAST_UPDATED_TIME"   	timestamp NULL);

CREATE TABLE ."Media"  ( 
	"id"                  	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK"	bigint NULL,
	"Url"                 	varchar(1024) NULL,
	"MediaType"           	char(5) NULL,
	"PrimaryMedia"        	BOOLEAN NULL,
	"Credit"              	varchar(255) NULL,
	"Caption"             	varchar(1000) NULL,
	"LAST_UPDATED_TIME"   	timestamp NULL);

CREATE TABLE "Prefs"  ( 
	"NodeName" 	nvarchar(255) NOT NULL,
	"PrefKey"  	nvarchar(50) NOT NULL,
	"PrefValue"	nvarchar(255) NOT NULL,
	PRIMARY KEY ("NodeName", "PrefKey"));

CREATE TABLE "SectionInfo"  ( 
	"id"                  	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK"	bigint NOT NULL,
	"Header"              	varchar(30) NOT NULL,
	"Label"               	varchar(50) NOT NULL,
	"Information"         	varchar(5000) NULL);

CREATE TABLE "UniqueID"  ( 
	"tablename"	varchar(200) NOT NULL,
	"nextid"   	bigint NULL,
	PRIMARY KEY ("tablename"));

CREATE TABLE "Usage"  ( 
	"id"                   	bigint PRIMARY KEY NOT NULL,
	"ConceptDelegateID_FK" 	bigint NULL,
	"EmbargoExpirationDate"	timestamp NULL,
	"Specification"        	varchar(1000) NULL,
	"LAST_UPDATED_TIME"    	timestamp NULL);

CREATE TABLE "UserAccount"  ( 
	"id"               	bigint PRIMARY KEY NOT NULL,
	"UserName"         	varchar(50) NOT NULL,
	"Password"         	varchar(50) NULL,
	"Role"             	varchar(10) NULL,
	"LAST_UPDATED_TIME"	timestamp NULL,
	"Affiliation"      	varchar(50) NULL,
	"FirstName"        	varchar(50) NULL,
	"LastName"         	varchar(50) NULL,
	"Email"            	varchar(50) NULL,
	UNIQUE("UserName"));

CREATE UNIQUE INDEX "idx_Artifact_CK"
	ON "Artifact"("ConceptDelegateID_FK", "GroupId", "ArtifactId", "Version", "Classifier");

CREATE INDEX "idx_Artifact_FK1"
	ON "Artifact"("ConceptDelegateID_FK");

CREATE INDEX "idx_Artifact_LUT"
	ON "Artifact"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_ConceptDelegate_FK1"
	ON "ConceptDelegate"("ConceptID_FK");

CREATE  INDEX "idx_ConceptDelegate_LUT"
	ON "ConceptDelegate"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_ConceptName_FK1"
	ON "ConceptName"("ConceptID_FK");

CREATE  INDEX "idx_ConceptName_LUT"
	ON "ConceptName"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_ConceptName_name"
	ON "ConceptName"("ConceptName");

CREATE  INDEX "idx_Concept_FK1"
	ON "Concept"("ParentConceptID_FK");

CREATE  INDEX "idx_Concept_LUT"
	ON "Concept"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_History_FK1"
	ON "History"("ConceptDelegateID_FK");

CREATE  INDEX "idx_History_LUT"
	ON "History"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_LinkRealization_FK1"
	ON "LinkRealization"("ConceptDelegateID_FK");

CREATE  INDEX "idx_LinkRealization_LUT"
	ON "LinkRealization"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_LinkTemplate_FK1"
	ON "LinkTemplate"("ConceptDelegateID_FK");

CREATE  INDEX "idx_LinkTemplate_LUT"
	ON "LinkTemplate"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_Media_LUT"
	ON "Media"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_Prefs"
	ON "Prefs"("NodeName", "PrefKey");

CREATE  INDEX "idx_SectionInfo_FK1"
	ON "SectionInfo"("ConceptDelegateID_FK");

CREATE  INDEX "idx_Usage_FK1"
	ON "Usage"("ConceptDelegateID_FK");

CREATE  INDEX "idx_Usage_LUT"
	ON "Usage"("LAST_UPDATED_TIME");

CREATE  INDEX "idx_UserAccount_UserName"
	ON "UserAccount"("UserName");


ALTER TABLE "UserAccount"
	ADD CONSTRAINT "uc_UserAccount_UserName"
	UNIQUE ("UserName") NOT ENFORCED 
	WITH (
		DATA_COMPRESSION = NONE
	) ON [PRIMARY]
GO
ALTER TABLE "ConceptDelegate"
	ADD CONSTRAINT "ConceptDelegate_FK1"
	FOREIGN KEY("ConceptID_FK")
	REFERENCES "Concept"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "ConceptDelegate"
	NOCHECK CONSTRAINT "ConceptDelegate_FK1"
GO
ALTER TABLE "Artifact" WITH NOCHECK
	ADD CONSTRAINT "Artifact_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "ConceptName" WITH NOCHECK
	ADD CONSTRAINT "ConceptName_FK1"
	FOREIGN KEY("ConceptID_FK")
	REFERENCES "Concept"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "History" WITH NOCHECK
	ADD CONSTRAINT "History_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "LinkRealization" WITH NOCHECK
	ADD CONSTRAINT "LinkRealization_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "LinkTemplate" WITH NOCHECK
	ADD CONSTRAINT "LinkTemplate_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "Media" WITH NOCHECK
	ADD CONSTRAINT "Media_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "SectionInfo" WITH NOCHECK
	ADD CONSTRAINT "SectionInfo_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
ALTER TABLE "Usage" WITH NOCHECK
	ADD CONSTRAINT "Usage_FK1"
	FOREIGN KEY("ConceptDelegateID_FK")
	REFERENCES "ConceptDelegate"("id")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
	NOT FOR REPLICATION 
GO
