global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: Annosaurus
    static_configs:
      - targets: [annosaurus:8080]
  - job_name: Vampire-squid (portal)
    static_configs:
      - targets: [vampire-squid:8080]



  